/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package layout;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author samue
 */
public class layout_principal extends javax.swing.JFrame {
 CardLayout cardLayout;
    /**
     * Creates new form layout_ini
     */
    public layout_principal() {
        initComponents();
        initUI();
        iniciarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtInicio = new javax.swing.JLabel();
        txtRegistroAsis = new javax.swing.JLabel();
        txtControlAcceso = new javax.swing.JLabel();
        txtPlanificacionAct = new javax.swing.JLabel();
        txtLabMant = new javax.swing.JLabel();
        txtGestionLabs = new javax.swing.JLabel();
        txtReservaUsoLabs = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtInicio.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        txtInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtInicio.setText("Inicio");
        txtInicio.setToolTipText("");
        txtInicio.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(txtInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 160, 30));

        txtRegistroAsis.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        txtRegistroAsis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRegistroAsis.setText("Registro Asistencia");
        jPanel1.add(txtRegistroAsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 160, 30));

        txtControlAcceso.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        txtControlAcceso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtControlAcceso.setText("Control Acceso");
        jPanel1.add(txtControlAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 160, 40));

        txtPlanificacionAct.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        txtPlanificacionAct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPlanificacionAct.setText("Planificacion de Actividades");
        jPanel1.add(txtPlanificacionAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 160, 30));

        txtLabMant.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        txtLabMant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLabMant.setText("Laboratorio de Mantenimiento");
        jPanel1.add(txtLabMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 160, 30));

        txtGestionLabs.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        txtGestionLabs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtGestionLabs.setText("Gestion De Laboratorios");
        txtGestionLabs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtGestionLabsMousePressed(evt);
            }
        });
        jPanel1.add(txtGestionLabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 160, 30));

        txtReservaUsoLabs.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        txtReservaUsoLabs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtReservaUsoLabs.setText("Reserva y Uso de Laboratorios");
        txtReservaUsoLabs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReservaUsoLabsMouseClicked(evt);
            }
        });
        jPanel1.add(txtReservaUsoLabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 160, 40));

        panelContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelContentLayout = new javax.swing.GroupLayout(panelContent);
        panelContent.setLayout(panelContentLayout);
        panelContentLayout.setHorizontalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        panelContentLayout.setVerticalGroup(
            panelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        jPanel1.add(panelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 510, 390));
        panelContent.getAccessibleContext().setAccessibleParent(jPanel1);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/samuel/Inicio.png"))); // NOI18N
        Fondo.setPreferredSize(new java.awt.Dimension(720, 512));
        Fondo.setRequestFocusEnabled(false);
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleDescription("");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtReservaUsoLabsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReservaUsoLabsMouseClicked
        // TODO add your handling code here:
        panel_inicio panel = new panel_inicio();
        changeState(panel, "reserva");
       
        
        txtReservaUsoLabs.setForeground(Color.GRAY);
    }//GEN-LAST:event_txtReservaUsoLabsMouseClicked

    private void txtGestionLabsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGestionLabsMousePressed
        // TODO add your handling code here:
        panel_salas panel = new panel_salas();
        changeState(panel, "salas");
        txtGestionLabs.setForeground(Color.GRAY);
    }//GEN-LAST:event_txtGestionLabsMousePressed
   
    public void changeState(JPanel p, String name){
     try{
       
        panelContent.add(p,name);
        cardLayout.show(panelContent, name);
        initColorText();
       
        }catch(Exception e){
        JOptionPane.showConfirmDialog(panelContent, e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(layout_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new layout_principal().setVisible(true);
        });
    }
    
    private void initUI(){
        initColorText();
        panelContent.setBackground(Color.white);
    }
    
    private void initColorText(){
    txtControlAcceso.setForeground(Color.white);
        txtGestionLabs.setForeground(Color.white);
        txtInicio.setForeground(Color.white);
        txtLabMant.setForeground(Color.white);
        txtPlanificacionAct.setForeground(Color.white);
        txtRegistroAsis.setForeground(Color.white);
        txtReservaUsoLabs.setForeground(Color.white);
    }
    
    private void iniciarComponentes() {
     cardLayout = new CardLayout();
     panelContent.setLayout(cardLayout);
        setLocationRelativeTo(null);
        setResizable(false);
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelContent;
    private javax.swing.JLabel txtControlAcceso;
    private javax.swing.JLabel txtGestionLabs;
    private javax.swing.JLabel txtInicio;
    private javax.swing.JLabel txtLabMant;
    private javax.swing.JLabel txtPlanificacionAct;
    private javax.swing.JLabel txtRegistroAsis;
    private javax.swing.JLabel txtReservaUsoLabs;
    // End of variables declaration//GEN-END:variables

    
}
