/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package layout;

/**
 *
 * @author samue
 */
public class panel_inicio extends javax.swing.JPanel {

    /**
     * Creates new form panel_inicio
     */
    public panel_inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtReserva = new javax.swing.JLabel();
        txtVerReservas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        img_reserva = new javax.swing.JLabel();
        img_verReservas = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(520, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Reserva Y Uso De Laboratorios");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 400, -1));

        txtReserva.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        txtReserva.setForeground(new java.awt.Color(255, 255, 255));
        txtReserva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtReserva.setText("Reserva");
        add(txtReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 90, 30));

        txtVerReservas.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        txtVerReservas.setForeground(new java.awt.Color(255, 255, 255));
        txtVerReservas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtVerReservas.setText("Ver Reservas");
        add(txtVerReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/inicio/Rectangle 71.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(520, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(520, 400));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        img_reserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/inicio/reserva.png"))); // NOI18N
        img_reserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_reservaMouseClicked(evt);
            }
        });
        add(img_reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        img_verReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/inicio/verHorarios.png"))); // NOI18N
        add(img_verReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void img_reservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_reservaMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_img_reservaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img_reserva;
    private javax.swing.JLabel img_verReservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtReserva;
    private javax.swing.JLabel txtVerReservas;
    // End of variables declaration//GEN-END:variables
}
